{% set name = "dagster_graphql" %}
{% set version = "0.6.6" %}

{% set dash_name = name.replace('_', '-') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ dash_name[0] }}/{{ dash_name }}/{{ dash_name }}-{{ version }}.tar.gz"
  sha256: d740b3ed0df5ff9919ac29804b034a932db2c720a6e01174d109796d6e3aed28

build:
  number: 0
  noarch: python
  entry_points:
    - dagster-graphql = dagster_graphql.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - gevent
    - gevent-websocket >=0.10.1
    - graphene >=2.1.3
    - requests
    - dagster {{ version }}.*

test:
  imports:
    - dagster_graphql
    - dagster_graphql.client
    - dagster_graphql.schema
  commands:
    - dagster-graphql --help

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "The GraphQL frontend to python dagster."

extra:
  recipe-maintainers:
    - conda-forge/dagster
